"""Worker protocol — the component that does the actual coding.

A Worker receives a task string and produces a result report. Implementations
range from a local CLI agent (opencode) to any arbitrary command.
"""

from __future__ import annotations

from abc import ABC, abstractmethod


class WorkerResult:
    """Normalised outcome of one worker run."""

    def __init__(self, *, exit_code: int, summary: str, transcript: str = "") -> None:
        self.exit_code = exit_code
        self.summary = summary
        self.transcript = transcript

    def to_markdown(self) -> str:
        head = "# Result Report (generated by agent-bridge)\n\n"
        status = "ok" if self.exit_code == 0 else f"FAILED (exit {self.exit_code})"
        return head + f"## Status\n\n{status}\n\n## Coder Output\n\n{self.summary}\n"


class Worker(ABC):
    """Interface for the coding-agent side of the bridge."""

    @abstractmethod
    def run(self, task: str) -> WorkerResult:
        raise NotImplementedError