"""Report formatting — turn a raw worker run into a clean, readable report.

The report is the message the coding agent sends to the task manager, so
it should be *scannable*: a clear status, the task that was asked, a short
"what changed" summary, and the raw output collapsed at the end.
"""

from __future__ import annotations

from datetime import datetime


def build_report(*, task: str, status: str, summary: str, elapsed_s: float = 0.0,
                 extra_blocks: list[str] | None = None) -> str:
    """Compose a pretty markdown report for the manager.

    Args:
        task: the task that was given to the worker.
        status: short status line, e.g. ``ok`` or ``FAILED (exit 1)``.
        summary: the worker's output/summary text.
        elapsed_s: seconds the task took (0 = omitted).
        extra_blocks: optional extra markdown sections (e.g. git summary).
    """
    lines: list[str] = []
    lines.append("# Result Report")
    lines.append("")

    icon, label = _status_icon(status)
    lines.append(f"## Status\n\n{icon} **{label}**")
    if elapsed_s > 0:
        lines.append(f"\n_elapsed: {_fmt_elapsed(elapsed_s)}_")
    lines.append("")

    lines.append("## Task\n\n```\n{0}\n```\n".format(task.strip()))

    lines.append("## What changed\n")
    lines.append(summary.strip() or "_(no output)_")
    lines.append("")

    for block in extra_blocks or []:
        if block:
            lines.append("---\n\n" + block.strip() + "\n")

    lines.append(f"---\n_generated by agent-bridge at {datetime.now().isoformat(timespec='seconds')}_")
    return "\n".join(lines) + "\n"


def _status_icon(status: str) -> tuple[str, str]:
    lowered = status.lower()
    if "ok" in lowered or "success" in lowered:
        return "✅", "Success"
    if "fail" in lowered or "error" in lowered:
        return "❌", status
    return "➖", status


def _fmt_elapsed(seconds: float) -> str:
    if seconds >= 60:
        return f"{int(seconds // 60)}m {int(seconds % 60)}s"
    return f"{seconds:.1f}s"